spring:
  application:
    name: service-inventory
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/ecomm_inventory
    password: secret

server:
  port: '8083'

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

